export const INITIAL_GEOLOCATION = "INITIAL_GEOLOCATION";
export const UPDATE_VENDOR_LIST = "UPDATE_VENDOR_LIST";
export const SET_MAIN_TAP = "SET_MAIN_TAP";
export const SET_SEARCH_TAP = "SET_SEARCH_TAP";
export const SET_MY_LIST_TAP = "SET_MY_LIST_TAP";
export const SET_EXTRA_TAP = "SET_EXTRA_TAP";
export const SET_FILTER_BY_DISTANCE = "SET_FILTER_BY_DISTANCE";
export const SET_FILTER_BY_FAVORITE = "SET_FILTER_BY_FAVORITE";
export const SET_FILTER_BY_COMMENT = "SET_FILTER_BY_COMMENT";
export const ADD_VENDOR_LIST_PAGE_NUMBER = "ADD_VENDOR_LIST_PAGE_NUMBER";
export const UPDATE_VENDOR_LIST_DISTANCE = "UPDATE_VENDOR_LIST_DISTANCE";
export const RESET_VENDOR_LIST_PAGE_NUMBER = "RESET_VENDOR_LIST_PAGE_NUMBER";
export const RESET_VENDOR_LIST = "RESET_VENDOR_LIST";
export const STOP_VENDORLIST_INFINITY_SCROLL =
  "STOP_VENDORLIST_INFINITY_SCROLL";
export const RESUME_VENDORLIST_INFINITY_SCROLL =
  "RESUME_VENDORLIST_INFINITY_SCROLL";
export const ACTIVATE_SCROLL_LOADING = "ACTIVATE_SCROLL_LOADING";
export const DE_ACTIVATE_SCROLL_LOADING = "DE_ACTIVATE_SCROLL_LOADING";
export const UPDATE_SEARCHED_VENDOR_LIST = "UPDATE_SEARCHED_VENDOR_LIST";
export const RESET_SEARCHED_VENDOR_LIST = "RESET_SEARCHED_VENDOR_LIST";
export const UPDATE_VENDOR_LIST_TOTAL_NUMBER =
  "UPDATE_VENDOR_LIST_TOTAL_NUMBER";
export const UPDATE_VENDOR_DETAIL_INFO = "UPDATE_VENDOR_DETAIL_INFO";
export const UPDATE_VENDOR_DETAIL_ID = "UPDATE_VENDOR_DETAIL_ID";
export const SET_VENDOR_DETAIL_STATUS_TAP_TO_MENU =
  "SET_VENDOR_DETAIL_STATUS_TAP_TO_MENU";
export const SET_VENDOR_DETAIL_STATUS_TAP_TO_INFO =
  "SET_VENDOR_DETAIL_STATUS_TAP_TO_INFO";
export const SET_VENDOR_DETAIL_STATUS_TAP_TO_REVIEW =
  "SET_VENDOR_DETAIL_STATUS_TAP_TO_REVIEW";
export const UPDATE_AUTHORIZED_USER_DATA = "UPDATE_AUTHORIZED_USER_DATA";
export const UPDATE_VENDOR_COMMENT_LIST = "UPDATE_VENDOR_COMMENT_LIST";
export const UPDATE_MY_FAVORITE_LIST = "UPDATE_MY_FAVORITE_LIST";
export const ADD_FAVORITE_IN_VENDOR_DETAILINFO =
  "ADD_FAVORITE_IN_VENDOR_DETAILINFO";
export const REMOVE_FAVORITE_IN_VENDOR_DETAILINFO =
  "REMOVE_FAVORITE_IN_VENDOR_DETAILINFO";
export const UPDATE_SEARCH_KEY_WORD = "UPDATE_SEARCH_KEY_WORD";
