export const INITIAL_GEOLOCATION = "INITIAL_GEOLOCATION";
export const UPDATE_VENDOR_LIST = "UPDATE_VENDOR_LIST";
export const SET_MAIN_TAP = "SET_MAIN_TAP";
export const SET_SEARCH_TAP = "SET_SEARCH_TAP";
export const SET_MY_LIST_TAP = "SET_MY_LIST_TAP";
export const SET_EXTRA_TAP = "SET_EXTRA_TAP";
export const SET_FILTER_BY_DISTANCE = "SET_FILTER_BY_DISTANCE";
export const SET_FILTER_BY_FAVORITE = "SET_FILTER_BY_FAVORITE";
export const SET_FILTER_BY_COMMENT = "SET_FILTER_BY_COMMENT";
export const ADD_VENDOR_LIST_PAGE_NUMBER = "ADD_VENDOR_LIST_PAGE_NUMBER";
export const UPDATE_VENDOR_LIST_DISTANCE = "UPDATE_VENDOR_LIST_DISTANCE";
export const RESET_VENDOR_LIST_PAGE_NUMBER = "RESET_VENDOR_LIST_PAGE_NUMBER";
export const RESET_VENDOR_LIST = "RESET_VENDOR_LIST";
export const STOP_VENDORLIST_INFINITY_SCROLL =
  "STOP_VENDORLIST_INFINITY_SCROLL";
export const RESUME_VENDORLIST_INFINITY_SCROLL =
  "RESUME_VENDORLIST_INFINITY_SCROLL";
export const ACTIVATE_SCROLL_LOADING = "ACTIVATE_SCROLL_LOADING";
export const DE_ACTIVATE_SCROLL_LOADING = "DE_ACTIVATE_SCROLL_LOADING";
